version: '3.7'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    restart: always
    volumes:
        - ./volume/mqtt/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
        - ./volume/mqtt/log:/mosquitto/config/log
        - ./volume/mqtt/data:/mosquitto/config/data
    ports:
      - 9100:9100
      - 9001:9001
